version: '3.6'

services:

  #API Gateway
  api-gateway:
    image: shial/api-gateway:0.0.1
    restart: always
    ports:
      - 5000:80
    environment:
      AUTH: http://user-service:80/users/id
      HOST:users: "{\"host\":\"http://user-service:80/\",\"loginRequired\":false}"

  #User Service
  user-service:
    image: shial/user-service:0.0.1
    restart: always
    environment:
      PSQL_DATABASE_URL: ${PSQL_DATABASE_URL}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
