version: '3.6'

services:

  #API Gateway
  api-gateway:
    image: shial/api-gateway:0.0.4
    restart: unless-stopped
    ports:
      - 5000:80
    environment:
      AUTH: http://user-service:81/users/id
      HOST:users: "{\"host\":\"http://user-service:81/\",\"loginRequired\":false}"

  #User Service
  user-service:
    image: shial/user-service:0.0.4
    restart: unless-stopped
    environment:
      PSQL_DATABASE_URL: ${PSQL_DATABASE_URL}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
