version: '3.6'

services:

  #API Gateway
  api-gateway:
    image: shial/api-gateway:0.0.5
    restart: unless-stopped
    ports:
      - 80:3000
    environment:
      AUTH: http://auth-service:3001/users/id
      HOST_users: "{\"host\":\"http://auth-service:3001/\",\"loginRequired\":false}"
      HOST_profiles: "{\"host\":\"http://profile-service:3002/\",\"loginRequired\":true}"

  #Auth Service
  auth-service:
    image: shial/user-service:0.0.8
    restart: unless-stopped
    environment:
      PSQL_DATABASE_URL: ${PSQL_DATABASE_URL}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
  
  #Profile Service
  profile-service:
    image: shial/profile-service:0.0.4
    restart: unless-stopped
    environment:
      PSQL_DATABASE_URL: ${PSQL_PROFILE_DATABASE_URL}
