version: '3.6'

services:

  #API Gateway
  api-gateway:
    image: shial/api-gateway:0.0.10
    restart: unless-stopped
    ports:
      - 80:3000
    environment:
      AUTH: http://auth-service:3001/users/id
      HOST_users: "{\"host\":\"http://auth-service:3001/\",\"loginRequired\":false}"
      HOST_profiles: "{\"host\":\"http://profile-service:3002/\",\"loginRequired\":true}"
      HOST_festivals: "{\"host\":\"http://product-service:3003/\",\"loginRequired\":true}"

  #Auth Service
  auth-service:
    image: shial/user-service:0.0.9
    restart: unless-stopped
    environment:
      PSQL_DATABASE_URL: ${PSQL_DATABASE_URL}
      FACEBOOK_APP_SECRET: ${FACEBOOK_APP_SECRET}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      TOKEN_EXPIRATION_INTERVAL: ${TOKEN_EXPIRATION_INTERVAL}
  
  #Profile Service
  profile-service:
    image: shial/profile-service:0.0.8
    restart: unless-stopped
    environment:
      PSQL_DATABASE_URL: ${PSQL_PROFILE_DATABASE_URL}

  #Festivals Service
  product-service:
    image: shial/product-service:0.0.6
    restart: unless-stopped
    environment:
      PSQL_DATABASE_URL: ${PSQL_PRODUCT_DATABASE_URL}
